---

kind: Namespace
apiVersion: v1
metadata:
  name: example-app
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: example-app
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          command:
            - python
          args:
            - '-m'
            - http.server
            - '8080'
            - '--directory'
            - /tmp
          image: >-
            quay.io/fjacquinrh/ubi8-toolbox
          ports:
            - containerPort: 8080
              name: http
---

apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: example-app
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
      
---
 
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: myapp
  namespace: example-app
spec:
  to:
    kind: Service
    name: myapp
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
